/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NKVqR4xHn46
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function MainPage() {
  return (
    (<div className="relative">
      <div className="absolute top-0 left-0 right-0">
        <nav className="flex justify-between items-center px-8 py-4">
          <span className="text-xl font-bold">proske.</span>
          <ul className="flex space-x-4">
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Home
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Company
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Services
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Software Development
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Case Studies
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                News
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Contact
              </Link>
            </li>
          </ul>
        </nav>
      </div>
      <div
        className="h-screen bg-[url(/placeholder.svg?height=800&width=1600)] bg-cover bg-center flex flex-col justify-center items-center text-center">
        <h1 className="text-5xl font-bold text-white mb-4">MAKING THE COMPLEX SIMPLE</h1>
        <p className="text-white max-w-md mb-8">
          THROUGH A STRATEGIC APPROACH TO EVENTS & LIVE MARKETING, SOFTWARE DEVELOPMENT, AND DIGITAL SOLUTIONS
        </p>
        <ChevronDownIcon className="text-white animate-bounce w-6 h-6" />
      </div>
      <div className="bg-gray-900 py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto text-center text-white">
          <h2 className="text-3xl font-bold mb-4">Software Development</h2>
          <p className="mb-8">
            At proske., we specialize in custom software development, leveraging the latest technologies to create
            innovative solutions that solve complex problems. Our team of skilled developers work closely with clients
            to understand their unique needs and deliver tailored applications that drive business growth and
            efficiency.
          </p>
          <Button size="lg" variant="primary">
            Learn More
          </Button>
        </div>
      </div>
      <div className="bg-gray-100 py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <CodeIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Application Development</h3>
            <p className="text-gray-600 mb-4">
              Our team of skilled developers create custom applications that solve complex problems and drive business
              growth.
            </p>
            <Button size="sm" variant="secondary">
              Learn More
            </Button>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <GlobeIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Web Development</h3>
            <p className="text-gray-600 mb-4">
              We design and develop modern, responsive websites that engage users and drive results.
            </p>
            <Button size="sm" variant="secondary">
              Learn More
            </Button>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <BriefcaseIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Business Administration Systems</h3>
            <p className="text-gray-600 mb-4">
              Our custom business administration systems streamline operations and improve efficiency.
            </p>
            <Button size="sm" variant="secondary">
              Learn More
            </Button>
          </div>
        </div>
      </div>
      <div className="bg-gray-900 py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <SmartphoneIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">WhatsApp</h3>
            <p className="text-gray-600 mb-4">Reach out to us on WhatsApp for quick assistance.</p>
            <Link
              className="inline-flex items-center justify-center rounded-md bg-green-500 px-4 py-2 text-white shadow transition-colors hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
              href="#"
              target="_blank">
              <SmartphoneIcon className="mr-2 w-5 h-5" />
              Contact Us
            </Link>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <MailIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Email</h3>
            <p className="text-gray-600 mb-4">Send us a message and we'll get back to you as soon as possible.</p>
            <form className="space-y-4">
              <Input className="w-full" placeholder="Enter your email" type="email" />
              <Textarea className="w-full" placeholder="Enter your message" />
              <Button className="w-full" type="submit" variant="primary">
                Send Message
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>)
  );
}

function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function GlobeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path
        d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function SmartphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>)
  );
}
