/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NKVqR4xHn46
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function MainPage() {
  return (
    (<div className="relative">
      <div className="absolute top-0 left-0 right-0">
        <nav className="flex justify-between items-center p-8 shadow-2xl bg-white bg-opacity-10">
          <span className="text-2xl font-bold text-white">Horizon</span>
          <ul className="flex space-x-4">
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Inicio
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Nosotros
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Servicios
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Casos de éxito
              </Link>
            </li>
            <li>
              <Link className="text-white hover:text-opacity-75" href="#">
                Contacto
              </Link>
            </li>
          </ul>
        </nav>
      </div>
      <div
        className="h-screen bg-[url(/bg-ciudad.jpg?height=800&width=1600)] bg-cover bg-center flex flex-col justify-center items-center text-center">
        <h1 className="text-5xl font-bold text-white mb-4">CREANDO NUEVAS REALIDADES</h1>
        <p className="text-white max-w-md mb-8">
          A TRAVÉS DE SOLUCIONES TECNOLÓGICAS INNOVADORAS PARA PROBLEMAS COMPLEJOS Y EL CRECIMIENTO DIGITAL
        </p>
        <ChevronDownIcon className="text-white animate-bounce w-6 h-6" />
      </div>
      <div className="bg-gray-900 py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto text-center text-white">
          <h2 className="text-3xl font-bold mb-4">Desarrollo de Software</h2>
          <p className="mb-8">
            En Horizon, nos especializamos en el desarrollo de servicios de software, aprovechando las últimas
            tecnologías para crear soluciones innovadoras que resuelvan retos empresariales. Nuestro equipo de
            desarrolladores  y soporte trabaja en estrecha colaboración con los clientes para comprender sus necesidades
            únicas y ofrecer aplicaciones que impulsen el crecimiento y la eficiencia empresarial.
          </p>
          <Button size="lg" variant="primary">
            Conoce Horizon
          </Button>
        </div>
      </div>
      <div className="bg-gray-100 py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <CodeIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Desarrollo de Aplicaciones</h3>
            <p className="text-gray-600 mb-4">
              Creamos aplicaciones que resuelven problemas, mejoran la interacción e impulsan el crecimiento.
            </p>
            <Button size="sm" variant="secondary">
              Conocer más
            </Button>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <GlobeIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2 min-h-[4rem]">Desarrollo Web</h3>
            <p className="text-gray-600 mb-4">
              Diseñamos y desarrollamos sitios web modernos y receptivos que involucran a los usuarios.
            </p>
            <Button size="sm" variant="secondary">
              Conocer más
            </Button>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <BriefcaseIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Sistemas Administrativos</h3>
            <p className="text-gray-600 mb-4">
              Nuestros sistemas de administración empresarial optimizan las operaciones y mejoran la eficiencia.
            </p>
            <Button size="sm" variant="secondary">
              Conocer más
            </Button>
          </div>
        </div>
      </div>
      <div className="bg-gray-900 py-12 px-4 md:px-8">
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <SmartphoneIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">WhatsApp</h3>
            <p className="text-gray-600 mb-4">
              Ponte en contacto con nosotros en WhatsApp para obtener asistencia rápida.</p>
            <Link
              className="inline-flex items-center justify-center rounded-md bg-green-500 px-4 py-2 text-white shadow transition-colors hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
              href=""
              target="_blank">
              <SmartphoneIcon className="mr-2 w-5 h-5" />
              Contáctanos
            </Link>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 text-center">
            <MailIcon className="text-gray-900 w-12 h-12 mb-4" />
            <h3 className="text-2xl font-bold mb-2">Email</h3>
            <p className="text-gray-600 mb-4">
              Envíanos un mensaje y te responderemos lo antes posible.</p>
            <form className="space-y-4">
              <Input className="w-full" placeholder="Ingresa tu email" type="email" />
              <Textarea className="w-full" placeholder="Ingresa tu mensaje" />
              <Button className="w-full" type="submit" variant="primary">
                Enviar mensaje
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>)
  );
}

function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function GlobeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path
        d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function SmartphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>)
  );
}
